[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "5000"

[phases.install]
cmds = ["npm ci"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[staticAssets]
publicDir = "dist/public"

[providers]
node = "20"