providers = ["node"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "5000"

[phases.install]
cmds = ["npm ci"]

[phases.build]
dependsOn = ["install"]
cmds = [
  "vite build",
  "esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --define:import.meta.dirname='process.cwd()'"
]

[staticAssets]
publicDir = "dist/public"